[tool.pytest.ini_options]
addopts = "--strict-markers -v --cov=src/did --cov=src/gdid --cov-report=term-missing --cov-report=html --cov-fail-under=90"
testpaths = ["tests"]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    gui: marks GUI tests
log_file = pytest.log
log_file_level = INFO
