site_name: evid
repo_url: https://github.com/evidlabel/evid
theme:
  name: material
  font:
    text: Ubuntu Sans
    code: Ubuntu Mono
  palette:
    scheme: slate
    primary: orange
    accent: green 
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Development: development.md
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

