[project]
name = "evid"
version = "0.2.1"
description = "document logger, adder of metadata"
authors = [{ name = "evid 210122431+evidlabel@users.noreply.github.com" }]
requires-python = ">=3.11,<4.0"
readme = "README.md"
license = "MIT"
dependencies = [
    "arrow>=1.3.0,<2",
    "pymupdf>=1.25.2,<2",
    "pypdf>=5.0.1,<6",
    "pyqt6>=6.7.0,<7",
    "pyyaml~=6.0",
    "bibtexparser>=1.4.3",
    "demoji>=1.1.0,<2",
    "pandas>=2.2.3,<3",
    "gitpython>=3.1.43,<4",
    "beautifulsoup4>=4.12.3,<5",
    "rich>=13.7.1,<14",  # Added for colored logging
    "rich-click>=1.8.3,<2",  # Added for enhanced CLI
    "pydantic>=2.9.2,<3",  # Added for validation
    "numpy>=2.1.2,<3",  # Added for vectorization
    "treeclick @ git+https://github.com/wr1/treeclick.git@master",
]

[project.scripts]
evid = "evid.cli.main:main"

[project.optional-dependencies]
dev = [
    "pytest~=7.0",
    "pytest-qt>=4.2.0,<5",
    "fitz>=0.0.1.dev2,<0.0.2",
    "mkdocs>=1.6.1,<2",  # Added for documentation
    "mkdocs-material",
    "uv>=0.4.22,<1",  # Prefer uv for installation
]

[tool.hatch.build.targets.sdist]
include = ["src/evid"]

[tool.hatch.build.targets.wheel]
include = ["src/evid"]

[tool.hatch.build.targets.wheel.sources]
"src/evid" = "evid"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true