[project]
name = "evid"
version = "0.1.4"
description = "document logger, adder of metadata"
authors = [{ name = "evid 210122431+evidlabel@users.noreply.github.com" }]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = "MIT"
dependencies = [
    "arrow>=1.3.0,<2",
    "pymupdf>=1.25.2,<2",
    "pypdf>=5.0.1,<6",
    "pyqt6>=6.7.0,<7",
    "pyyaml~=6.0",
    "bibtexparser>=1.4.3",
    "demoji>=1.1.0,<2",
    "pandas>=2.2.3,<3",
    "gitpython>=3.1.43,<4",
    "beautifulsoup4>=4.12.3,<5",
]

[project.scripts]
evid = "evid.cli.main:main"

[dependency-groups]
dev = [
    "pytest~=7.0",
    "pytest-qt>=4.2.0,<5",
    "fitz>=0.0.1.dev2,<0.0.2",
]

[tool.hatch.build.targets.sdist]
include = ["src/evid"]

[tool.hatch.build.targets.wheel]
include = ["src/evid"]

[tool.hatch.build.targets.wheel.sources]
"src/evid" = "evid"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
