layers:
  - id: background
    evidence: [t2]
    grounding: grounding/background.md

  - id: analysis
    evidence: [t2, lit.t4, 6dc42bf7857df90147c44503b23ae908]
    grounding: grounding/analysis.md
    layers:
      - id: analysis-sub
        evidence: [t2]
        grounding: grounding/analysis_sub.md

final_question: grounding/final_question.md
