name: CI

on:
  push:
    branches:
      - master
      - cli
  pull_request:
    branches:
      - master
      

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libegl1 libopengl0 libxcb-glx0 libxkbcommon0 libxkbcommon-x11-0 libxcb-xinerama0 libxcb-xinput0 libxcb-keysyms1 libxcb-image0 libxcb-shm0 libxcb-icccm4 libxcb-sync1 libxcb-xfixes0 libxcb-shape0 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-xkb1 libx11-xcb1 libgl1 libglu1-mesa libfontconfig1 libdbus-1-3 libxi6 libxrender1 libxcb-cursor0

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv .venv --seed
          uv pip install -e .[dev]

      - name: Run tests
        run: |
          source .venv/bin/activate
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" uv run pytest -v 

  deploy-docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv venv .venv --seed
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Build MkDocs site
        run: |
          source .venv/bin/activate
          uv run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./site
          force_orphan: true
